# Generated by Django 5.1.4 on 2024-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('image', models.ImageField(upload_to='music_image/')),
                ('file', models.FileField(upload_to='music_file')),
            ],
        ),
    ]
