# Generated by Django 5.1.4 on 2024-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to='music_file/'),
        ),
    ]
